import Head from "next/head";
import { useEffect, useState, useLayoutEffect, useRef } from "react";
import styles from "../styles/Home.module.scss";
import stylesNav from "../styles/Navbar.module.scss";
import IntroSecondary from "./components/intro-secondary";
import IntroTertiary from "./components/intro-tertiary";
import Intro from "./components/intro";
import Navbar from "./components/navbar";

export default function Home({ theme, updateTheme }) {
  const [width, setWidth] = useState(0);
  const introSecondary = useRef();
  const introTertiary = useRef();

  useEffect(() => {
    function handleResize() {
      setWidth(window.innerWidth);
    }

    window.addEventListener("resize", handleResize);

    handleResize();

    return () => {
      window.removeEventListener("resize", handleResize);
    };
  }, [setWidth]);

  return (
    <div className={styles.sheet_background}>
      <Head>
        <title>Zen Litter Box</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {<Navbar width={width} setTheme={updateTheme} theme={theme} />}
      <div className={styles.sheet_container}>
        <Intro scrollReference={introSecondary} />
        <IntroSecondary
          reference={introSecondary}
          scrollReference={introTertiary}
        />
        <IntroTertiary reference={introTertiary} />
      </div>
    </div>
  );
}
