import Head from "next/head";
import { useEffect, useState, useLayoutEffect, useRef, use } from "react";
import styles from "../styles/Home.module.scss";
import stylesNav from "../styles/Navbar.module.scss";
import IntroSecondary from "./components/home/intro-secondary";
import IntroTertiary from "./components/home/intro-tertiary";
import Intro from "./components/home/intro";
import Navbar from "./components/navbar";
import { motion, useScroll, useSpring } from "framer-motion";

export interface HomeProps {
  width: number;
}

export default function Home({ width }: HomeProps) {
  const introSecondary = useRef();
  const introTertiary = useRef();
  const data_x = width < 768 ? "18" : "200";

  return (
    <div className={styles.sheet_background}>
      <Head>
        <title>Zen Litter Box</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script
          data-name="BMC-Widget"
          data-cfasync="false"
          src="https://cdnjs.buymeacoffee.com/1.0.0/widget.prod.min.js"
          data-id="harissocool"
          data-description="Support me on Buy me a coffee!"
          data-message=""
          data-color="#40DCA5"
          data-position="Right"
          data-x_margin={data_x}
          data-y_margin="18"
        ></script>
      </Head>

      <div className={styles.sheet_container}>
        <Intro scrollReference={introSecondary} />
        <IntroSecondary
          reference={introSecondary}
          scrollReference={introTertiary}
        />
        <IntroTertiary reference={introTertiary} />
      </div>
    </div>
  );
}
