import Head from "next/head";
import { useEffect, useState, useLayoutEffect, useRef, use } from "react";
import styles from "../styles/Home.module.scss";
import stylesNav from "../styles/Navbar.module.scss";
import IntroSecondary from "./components/intro-secondary";
import IntroTertiary from "./components/intro-tertiary";
import Intro from "./components/intro";
import Navbar from "./components/navbar";
import { motion, useScroll, useSpring } from "framer-motion";

interface HomeProps {
  theme: string;
  updateTheme: (newTheme: string) => void;
}

export default function Home({ theme, updateTheme }: HomeProps) {
  const [width, setWidth] = useState(0);
  const [showMinushkaResult, setShowMinushkaResult] = useState(false);
  const introSecondary = useRef();
  const introTertiary = useRef();
  const variants = {
    open: { opacity: 0.9, y: 0, transition: { duration: 1 } },
    closed: { opacity: 0, y: "-100%", transition: { duration: 1 } },
  };

  useEffect(() => {
    function handleResize() {
      setWidth(window.innerWidth);
    }
    window.addEventListener("resize", handleResize);
    handleResize();
    return () => {
      window.removeEventListener("resize", handleResize);
    };
  }, [setWidth]);

  useEffect(() => {
    setTimeout(() => {
      setShowMinushkaResult(false);
    }, 5000);
  }, [showMinushkaResult]);

  return (
    <div className={styles.sheet_background}>
      <Head>
        <title>Zen Litter Box</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script
          data-name="BMC-Widget"
          data-cfasync="false"
          src="https://cdnjs.buymeacoffee.com/1.0.0/widget.prod.min.js"
          data-id="harissocool"
          data-description="Support me on Buy me a coffee!"
          data-message=""
          data-color="#40DCA5"
          data-position="Right"
          data-x_margin="18"
          data-y_margin="18"
        ></script>
      </Head>
      {
        <Navbar
          width={width}
          setTheme={updateTheme}
          theme={theme}
          setShowMinushkaResult={setShowMinushkaResult}
        />
      }
      <motion.div
        animate={showMinushkaResult ? "open" : "closed"}
        variants={variants}
        initial={"closed"}
        className={styles.sheet_modal}
      >
        Minushka is napping!
      </motion.div>
      <div className={styles.sheet_container}>
        <Intro scrollReference={introSecondary} />
        <IntroSecondary
          reference={introSecondary}
          scrollReference={introTertiary}
        />
        <IntroTertiary reference={introTertiary} />
      </div>
    </div>
  );
}
